default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: labber_game_development

test:
  <<: *default
  database: labber_game_test

production:
  <<: *default
  database: labber_game_production
  username: labber
  password: <%= ENV['labber'] %>